### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Shifat7** [JohnVonNeumann/INF10002#1]
Where are the remaining tasks from 1-2 and 4-5?

**Comment by JohnVonNeumann** [comment]
![Nope](https://i.kym-cdn.com/photos/images/original/000/776/195/582.gif)

**Comment by Shifat7** [comment]
>:(

**Comment by JohnVonNeumann** [comment]
![image](https://user-images.githubusercontent.com/18162779/131447284-462a9f15-ad20-4a5d-97c8-dfcdaeec9fb7.png)
